In [2]:
using DelimitedFiles

using PyPlot
pygui(true)

true

In [4]:
# Julia script to change comma decimal sign to dot

# Function to convert comma decimal to dot
function convert_commas(input_file::String, output_file::String)
    # Read the input file
    content = read(input_file, String)

    # Replace ',' with '.'
    converted_content = replace(content, ',' => '.')

    # Write the converted data to the output file
    write(output_file, converted_content)

    println("Conversion completed. Check the '$output_file' file for results.")
end

# Define your input and output files
dir = "tangerine_FROG_50kHz"
input_file = "Ek.dat"  # Your input file name
output_file = "Ek.dat"  # Desired output file name

# Call the function to perform the conversion
convert_commas(joinpath(dir,input_file), joinpath(dir,output_file))

Conversion completed. Check the 'tangerine_FROG_50kHz\Ek.dat' file for results.


MIRRORS

In [35]:
path_m1 = joinpath("input", "mirrordata_0fs2.txt")

data = readdlm(path_m1, skipstart=1)

λ_m1 = data[:,1]     # read in wavelengths [nm]
R_m1 = data[:,2]     # read in reflectivity [%]
GDD_m1 = data[:,3]  # read in GDD [fs2]




path_m2 = joinpath("input", "mirrordata_-30fs2.txt")

data = readdlm(path_m2, skipstart=1)

λ_m2 = data[:,1]     # read in wavelengths [nm]
R_m2 = data[:,2]     # read in reflectivity [%]
GDD_m2 = data[:,3]  # read in GDD [fs2]

251-element Vector{Float64}:
    274.602
    440.228
    633.096
    675.624
    288.78
   -409.266
   -796.979
   -692.267
   -414.619
   -191.07
      ⋮
  -1582.87
  -1927.75
  -2446.49
  -3360.49
  -5263.92
  -9981.52
 -24309.7
 -76885.0
 -98453.1

In [36]:
fig, ax1 = plt.subplots()
ax1.set_title("Low GDD mirror from data")
ax1.plot(λ_m1, R_m1, label="reflectivity")
ax2 = ax1.twinx()
ax2.plot(λ_m1, GDD_m1, label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity [%]")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

fig, ax1 = plt.subplots()
ax1.set_title("High GDD mirror from data")
ax1.plot(λ_m2, R_m2, label="reflectivity [%]")
ax2 = ax1.twinx()
ax2.plot(λ_m2, GDD_m2, label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

plt.show()

MIRROR with 100% reflectivity and constant 0 GDD

In [37]:
λ_r100_0fs2 = collect(800.0 : 1300.0)
R_100_0fs2 = fill(100.0, length(λ_r100_0fs2))
GDD_0fs2 = zeros(length(λ_r100_0fs2))


λ_r100_neg_30fs2 = collect(800.0 : 1300.0)
R_100_neg_30fs2 = fill(100.0, length(λ_r100_neg_30fs2))
GDD_neg_30fs2 = fill(-30.0, length(λ_r100_neg_30fs2))

501-element Vector{Float64}:
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
   ⋮
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0

In [38]:
fig, ax1 = plt.subplots()
ax1.set_title("mirror with R = 100% and GDD = 0 fs2")
ax1.plot(λ_r100_0fs2, R_100_0fs2, label="reflectivity")
ax2 = ax1.twinx()
ax2.plot(λ_r100_0fs2, GDD_0fs2, linestyle="--", label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity [%]")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

fig, ax1 = plt.subplots()
ax1.set_title("mirror with R = 100% and GDD = -30 fs2")
ax1.plot(λ_r100_neg_30fs2, R_100_neg_30fs2, label="reflectivity")
ax2 = ax1.twinx()
ax2.plot(λ_r100_neg_30fs2, GDD_neg_30fs2, linestyle="--", label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity [%]")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

plt.show()

MIRRORS WITH REFLECTIVITY TAKEN FROM DATA BUT GDD SET CONSTANT TO 0 / -30 fs2 RESPECTIVELY

In [41]:
λ_R_data_0fs2 = λ_m1
R_data_0fs2 = R_m1
GDD_R_data_0fs2 = zeros(length(λ_R_data_0fs2))


λ_R_data_neg_30fs2 = λ_m2
R_data_neg_30fs2 = R_m2
GDD_R_data_neg_30fs2 = fill(-30.0, length(λ_R_data_neg_30fs2))

251-element Vector{Float64}:
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
   ⋮
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0
 -30.0

In [48]:
fig, ax1 = plt.subplots()
ax1.set_title("mirror with R taken from data and GDD = 0 fs2")
ax1.plot(λ_Rdata_0fs2, R_data_0fs2, label="reflectivity")
ax2 = ax1.twinx()
ax2.plot(λ_Rdata_0fs2, GDD_R_data_0fs2, linestyle="--", label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity [%]")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

fig, ax1 = plt.subplots()
ax1.set_title("mirror with R taken from data and GDD = -30 fs2")
ax1.plot(λ_R_data_neg_30fs2, R_data_neg_30fs2, label="reflectivity")
ax2 = ax1.twinx()
ax2.plot(λ_R_data_neg_30fs2, GDD_R_data_neg_30fs2, linestyle="--", label="GDD", color="orange")
ax1.set_ylim(-5, 105)
ax2.set_ylim(-50, 50)
ax1.set_xlabel("λ [nm]")
ax1.set_ylabel("reflectivity [%]")
ax2.set_ylabel("GDD [fs2]")
ax1.legend(loc="upper left")
ax2.legend(loc="upper right")
plt.tight_layout()

plt.show()

In [ ]:
λ_R_data_neg_30fs2 = λ_m2
R_data_neg_30fs2 = R_m2
GDD_R_data_neg_30fs2 = fill(-30.0, length(λ_R_data_neg_30fs2))

WRITING NEW TXT FILES FOR MIRRORS

In [43]:
# input units to work with MPC simulation script: [nm], [%], [fs2]

function write_data_to_file(filename, wavelength, reflectivity, GDD)
    # Open the file for writing
    open(filename, "w") do io
        # Write the header with tabs
        println(io, "m_wavelength\tm_R\tm_GDD")

        # Use writedlm with zip to write the data
        writedlm(io, zip(wavelength, reflectivity, GDD), '\t')#, fmt = "%.6f")
    end
end

write_data_to_file (generic function with 1 method)

In [ ]:
filename = joinpath("input", "mirror_R_100_GDD_0fs2.txt")
write_data_to_file(filename, λ_r100_0fs2, R_100_0fs2, GDD_0fs2)

filename = joinpath("input", "mirror_R_100_GDD_-30fs2.txt")
write_data_to_file(filename, λ_r100_neg_30fs2, R_100_neg_30fs2, GDD_neg_30fs2)

# filename = joinpath("input", "mirror_R_data_GDD_0fs2.txt")
# write_data_to_file(filename, λ_R_data_0fs2, R_data_0fs2, GDD_R_data_0fs2)

# filename = joinpath("input", "mirror_R_data_GDD_-30fs2.txt")
# write_data_to_file(filename, λ_R_data_neg_30fs2, R_data_neg_30fs2, GDD_R_data_neg_30fs2)